### ISSUE TITLE
Build with camlp5 6.00 broken

### ISSUE THREAD

**Issue by Zimmi48** [Zimmi48/bugzilla-test#2432]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 2432
Date: 2010-11-08 17:40:53 +0100
From: Andreas Bogk &lt;<andreas@andreas.org>&gt;
To:   
CC:   steph@glondu.net

Last updated: 2010-11-16 22:15:34 +0100

## Bugzilla Comment ID: 3796
Date: 2010-11-08 17:40:53 +0100
From: Andreas Bogk &lt;<andreas@andreas.org>&gt;

Coq won't compile with camlp5 version 6.00. Symptom:

File "parsing/pcoq.ml4", line 150, characters 10-18:
Error: Unbound value Gramext.val

This might as well be a camlp5 bug, somebody with more insight thanme should look into this. My workaround for now is using camlp5 5.15.

## Bugzilla Comment ID: 3797
Date: 2010-11-08 18:20:28 +0100
From: Andreas Bogk &lt;<andreas@andreas.org>&gt;

A patch fixing some of the issues was posted to the mailing list. https://sympa-roc.inria.fr/wws/arc/coqdev/2010-11/msg00013.html

## Bugzilla Comment ID: 3798
Date: 2010-11-08 23:41:18 +0100
From: Andreas Bogk &lt;<andreas@andreas.org>&gt;

According to the mail posted to the list:

https://sympa-roc.inria.fr/wws/arc/coqdev/2010-11/msg00014.html

at least two of the problems are actually bugs in camlp5.  However, compilation then fails at a later stage:

make --warn-undefined-variable --no-builtin-rules -f Makefile.stage2 "world"
make[1]: Entering directory `/home/andreas/coq-8.3'
Makefile.doc:188: warning: undefined variable `QUICK'
OCAMLC4   parsing/lexer.ml4
File "/tmp/camlpp989015", line 244, characters 2-6:
Error: This expression has type string ref
       but an expression was expected of type string
TOUCH     toplevel/mltop.ml
CHECK revision
OCAMLOPT4 parsing/lexer.ml4
File "/tmp/camlpp10570b", line 244, characters 2-6:
Error: This expression has type string ref
       but an expression was expected of type string
make[1]: *** [parsing/lexer.cmx] Error 2
rm toplevel/mltop.ml
make[1]: Leaving directory `/home/andreas/coq-8.3'
make: *** [world] Error 2

The offending lines read:

let store len x =
  if len >= String.length !buff then
    buff := !buff ^ String.create (String.length !buff);
  buff.[len] := x;
  succ len

with line 244 being the assignment "buff.[len] := x;".

## Bugzilla Comment ID: 3812
Date: 2010-11-12 22:16:23 +0100
From: Stephane Glondu &lt;<steph@glondu.net>&gt;

See https://sympa-roc.inria.fr/wws/arc/coqdev/2010-11/msg00016.html for patches that allow compilation of coq 8.3 with camlp5 6.01.

## Bugzilla Comment ID: 3816
Date: 2010-11-16 22:15:34 +0100
From: Stephane Glondu &lt;<steph@glondu.net>&gt;

The trunk and branch v8.3 of Coq now compile with Camlp5 6.02.0.
