### ISSUE TITLE
./configure should detect lablgtk version

### ISSUE THREAD

**Issue by Zimmi48** [Zimmi48/bugzilla-test#4423]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 4423
Date: 2015-11-12 14:57:58 +0100
From: @_gares
To:   
CC:   asr@eafit.edu.co, coq-bugs-redist@lists.gforge.inria.fr, @_ppedrot

Last updated: 2015-11-25 15:49:46 +0100

## Bugzilla Comment ID: 11252
Date: 2015-11-12 14:57:58 +0100
From: @_gares

As reported on coq-club, the beta3 fails to build on an ubuntu 12.04:

  $ make
  ...
  File "ide/preferences.ml", line 717, characters 16-45:
  Error: Unbound value GtkData.AccelMap.change_entry
  make[1]: *** [ide/preferences.cmo] Error 2

Additional information:
OS: Ubuntu 12.04

The API seems to be in 2.16 only (not in 2.14, the version in Ubuntu 12.04).

The configure script should detect that.

## Bugzilla Comment ID: 11264
Date: 2015-11-14 23:37:12 +0100
From: Andrés Sicard-Ramírez &lt;<asr@eafit.edu.co>&gt;

As I wrote in coq-club, as someone *unfamiliar* with the Ocaml toolchain, it seems odd that the versions of Objective Caml and Camlp5 in Ubuntu LTS 12.04 are supported, but the version of lablgtk doesn't.

## Bugzilla Comment ID: 11265
Date: 2015-11-15 12:00:54 +0100
From: @_gares

Unfortunately OCaml has no such a thing as "an OCaml platform".
Hence Linux distributions aggregate OCaml related libraries, but they do not necessarily pick the same versions or the same combination of libraries.  Typically developers look at the header files installed on the system, so if they see an API, they use it.  I guess the author of the code that fails to compile on your PC does not use the Ubuntu LTS you are using, as well the other developers and the test machines (they are on a LTS from 2014, IIRC). 

I hope this satisfies your curiosity and explains the oddity.

Said that, I think the configure script should check for the right version
of lablgtk2 and the doc should mention the required version too.  I mean, the compilation failure you saw should never reach a final user, it should be detected early by the configure script.  Hence the title of this bug report.

Thanks for testing 8.5 beta!

## Bugzilla Comment ID: 11266
Date: 2015-11-15 13:34:06 +0100
From: Andrés Sicard-Ramírez &lt;<asr@eafit.edu.co>&gt;

(In reply to comment #2)
> I hope this satisfies your curiosity and explains the oddity.

Yes. Thanks!

> Said that, I think the configure script should check for the right version
> of lablgtk2 and the doc should mention the required version too.  I mean,
> the compilation failure you saw should never reach a final user, it should
> be detected early by the configure script.

I agree, of course.

## Bugzilla Comment ID: 11309
Date: 2015-11-25 15:49:46 +0100
From: @_ppedrot

Fixed in 901a9b29.
