### ISSUE TITLE
Coq 8.3pl3 compilation error on FreeBSD

### ISSUE THREAD

**Issue by Zimmi48** [Zimmi48/bugzilla-test#2728]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 2728
Date: 2012-03-08 11:45:54 +0100
From: johans@coq.gletsjer.org
To:   
CC:   johans@coq.gletsjer.org, steph@glondu.net

Last updated: 2012-03-09 15:29:34 +0100

## Bugzilla Comment ID: 4872
Date: 2012-03-08 11:45:54 +0100
From: johans@coq.gletsjer.org

Created attachment 335
log of coq compilation

Coq 8.3pl3 fails to build on a modern 64-bit FreeBSD 9.0 system.
The build uses camlp5 version 6.0.5 with ocaml 3.12.1.

A full build log is attached. The fatal error is:

OCAMLC    pretyping/pretype_errors.mli
OCAMLOPT  pretyping/pretype_errors.ml
File "pretyping/pretype_errors.ml", line 48, characters 4-109:
Error: Unbound constructor Stdpp.Exc_located
gmake[1]: *** [pretyping/pretype_errors.cmx] Error 2

> Attached file: typescript (application/octet-stream, 62765 bytes)
> Description:   log of coq compilation

## Bugzilla Comment ID: 4875
Date: 2012-03-09 14:25:08 +0100
From: Stephane Glondu &lt;<steph@glondu.net>&gt;

This incompatibility is due to camlp5 6.05 (released last Sunday). If you are in a hurry, try with camlp5 6.04.

## Bugzilla Comment ID: 4876
Date: 2012-03-09 15:29:34 +0100
From: Stephane Glondu &lt;<steph@glondu.net>&gt;

Fixed in SVN v8.3 branch (r15025). It seems that the trunk and v8.4 branches were already camlp5 6.05-aware.
